// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Models;

#nullable disable

namespace Shop.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20231021173605_Create database")]
    partial class Createdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Models.Admin", b =>
                {
                    b.Property<string>("UserAdmin")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassAdmin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("UserAdmin")
                        .HasName("PK__ADMIN__AF86462BD99B60B4");

                    b.ToTable("ADMIN", (string)null);
                });

            modelBuilder.Entity("Shop.Models.Chitietdonthang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<decimal?>("Dongia")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int");

                    b.HasKey("MaDonHang", "MaSp")
                        .HasName("PK_CTDatHang");

                    b.HasIndex("MaSp");

                    b.ToTable("CHITIETDONTHANG", (string)null);
                });

            modelBuilder.Entity("Shop.Models.Danhmuc", b =>
                {
                    b.Property<int>("MaDm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDm"));

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDm")
                        .HasName("PK_DanhMuc");

                    b.ToTable("DANHMUC", (string)null);
                });

            modelBuilder.Entity("Shop.Models.Diachi", b =>
                {
                    b.Property<int>("MaDiaChi")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DiaChi");

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<string>("Sdt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TenNguoiNhann")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDiaChi");

                    b.HasIndex("MaKh");

                    b.ToTable("DIACHI", (string)null);
                });

            modelBuilder.Entity("Shop.Models.Dondathang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaVoucher")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Ngaydat")
                        .HasColumnType("date");

                    b.Property<DateTime?>("Ngaygiao")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenNguoiNhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tinhtranggiaohang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TongGia")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaDonHang")
                        .HasName("PK_DonDatHang");

                    b.HasIndex("MaKh");

                    b.ToTable("DONDATHANG", (string)null);
                });

            modelBuilder.Entity("Shop.Models.Khachhang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime");

                    b.Property<string>("Taikhoan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaKh")
                        .HasName("PK_Khachhang");

                    b.HasIndex(new[] { "Taikhoan" }, "UQ__KHACHHAN__7FB3F64FC08A3864")
                        .IsUnique()
                        .HasFilter("[Taikhoan] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__KHACHHAN__A9D105342273C2BD")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("Shop.Models.Khuyenmai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .HasColumnType("int");

                    b.Property<string>("CodeMaKhuyenMai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("GiaTri")
                        .HasColumnType("float");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("date");

                    b.Property<string>("LoaiMaKhuyenMai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenKhuyenMai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhuyenMai");

                    b.ToTable("KHUYENMAI", (string)null);
                });

            modelBuilder.Entity("Shop.Models.Loai", b =>
                {
                    b.Property<int>("MaL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaL"));

                    b.Property<int?>("MaDm")
                        .HasColumnType("int")
                        .HasColumnName("MaDM");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaL")
                        .HasName("PK_Loai");

                    b.HasIndex("MaDm");

                    b.ToTable("LOAI", (string)null);
                });

            modelBuilder.Entity("Shop.Models.Nhacungcap", b =>
                {
                    b.Property<int>("MaNcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNCC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNcc"));

                    b.Property<string>("Diachi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenNcc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenNCC");

                    b.HasKey("MaNcc")
                        .HasName("PK_NhaCungCap");

                    b.ToTable("NHACUNGCAP", (string)null);
                });

            modelBuilder.Entity("Shop.Models.NhanXet", b =>
                {
                    b.Property<int>("MaNhanXet")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int?>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaNhanXet");

                    b.ToTable("NhanXet", (string)null);
                });

            modelBuilder.Entity("Shop.Models.Sanpham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"));

                    b.Property<string>("Anhbia")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Giaban")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("MaL")
                        .HasColumnType("int");

                    b.Property<int?>("MaNcc")
                        .HasColumnType("int")
                        .HasColumnName("MaNCC");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Ngaycapnhat")
                        .HasColumnType("datetime");

                    b.Property<int?>("Soluongton")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("PK_SanPham");

                    b.HasIndex("MaL");

                    b.HasIndex("MaNcc");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("Shop.Models.Chitietdonthang", b =>
                {
                    b.HasOne("Shop.Models.Dondathang", "MaDonHangNavigation")
                        .WithMany("Chitietdonthangs")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_DonHang");

                    b.HasOne("Shop.Models.Sanpham", "MaSpNavigation")
                        .WithMany("Chitietdonthangs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("Shop.Models.Diachi", b =>
                {
                    b.HasOne("Shop.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Diachis")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_DIACHI_KHACHHANG");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("Shop.Models.Dondathang", b =>
                {
                    b.HasOne("Shop.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Dondathangs")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_Khachhang");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("Shop.Models.Loai", b =>
                {
                    b.HasOne("Shop.Models.Danhmuc", "MaDmNavigation")
                        .WithMany("Loais")
                        .HasForeignKey("MaDm")
                        .HasConstraintName("FK_DanhMuc");

                    b.Navigation("MaDmNavigation");
                });

            modelBuilder.Entity("Shop.Models.Sanpham", b =>
                {
                    b.HasOne("Shop.Models.Loai", "MaLNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("MaL")
                        .HasConstraintName("FK_Loai");

                    b.HasOne("Shop.Models.Nhacungcap", "MaNccNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("MaNcc")
                        .HasConstraintName("FK_NhaCungCap");

                    b.Navigation("MaLNavigation");

                    b.Navigation("MaNccNavigation");
                });

            modelBuilder.Entity("Shop.Models.Danhmuc", b =>
                {
                    b.Navigation("Loais");
                });

            modelBuilder.Entity("Shop.Models.Dondathang", b =>
                {
                    b.Navigation("Chitietdonthangs");
                });

            modelBuilder.Entity("Shop.Models.Khachhang", b =>
                {
                    b.Navigation("Diachis");

                    b.Navigation("Dondathangs");
                });

            modelBuilder.Entity("Shop.Models.Loai", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("Shop.Models.Nhacungcap", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("Shop.Models.Sanpham", b =>
                {
                    b.Navigation("Chitietdonthangs");
                });
#pragma warning restore 612, 618
        }
    }
}
